const ApiUrls = {
  LOGIN: '/auth/login',
  GET_ALL_DRIVES: '/drives/get-all',
  CREATE_DRIVE: '/drives/create',
  GET_DRIVE_DETAILS: '/drives/get-details',
  UPDATE_DRIVE: '/drives/update',
  CLOSE_DRIVE: '/drives/close',
  DELETE_DRIVE: '/drives/delete',
  REGISTER_CANDIDATE: '/registrations/register',
  GET_REGISTRATIONS: '/registrations/get-by-drive',
  GET_REGISTRATION_DETAILS: '/registrations/get-details',
  UPDATE_REG_STATUS: '/registrations/update-status',
  BULK_IMPORT_REGISTRATIONS: '/registrations/bulk-import',
  EVALUATE_ELIGIBILITY: '/eligibility/evaluate',
  BULK_EVALUATE: '/eligibility/bulk-evaluate',
  APPROVE_CANDIDATE: '/eligibility/approve',
  REJECT_CANDIDATE: '/eligibility/reject',
  GET_ELIGIBILITY: '/eligibility/get-by-drive',
  IMPORT_RESULT: '/results/import',
  BULK_IMPORT_RESULTS: '/results/bulk-import',
  GET_RESULTS: '/results/get-by-drive',
  UPLOAD_EVIDENCE: '/results/upload-evidence',
  ADD_VOUCHER_POOL: '/vouchers/add-pool',
  BULK_ADD_VOUCHERS: '/vouchers/bulk-add',
  ALLOCATE_VOUCHER: '/vouchers/allocate',
  AUTO_ALLOCATE: '/vouchers/auto-allocate',
  GET_VOUCHERS: '/vouchers/get-by-drive',
  REVOKE_VOUCHER: '/vouchers/revoke',
  REISSUE_VOUCHER: '/vouchers/reissue',
  MARK_REDEEMED: '/vouchers/mark-redeemed',
  GET_EXPIRING: '/vouchers/get-expiring',
  DRIVE_SUMMARY: '/reports/drive-summary',
  FUNNEL_DATA: '/reports/funnel',
  PASS_FAIL_TRENDS: '/reports/pass-fail-trends',
  VOUCHER_UTILIZATION: '/reports/voucher-utilization',
  OVERALL_STATS: '/reports/overall-stats',
  EXPORT_CSV: '/reports/export-csv',
  GET_AUDIT_LOGS: '/audit/get-logs',
  GET_AUDIT_BY_ENTITY: '/audit/get-by-entity',
  GET_COMMUNICATIONS: '/communications/get-by-registration',
}

export default ApiUrls
